#!/bin/sh

APPDIR=$(dirname "$0")
java -Djna.nosys=true -Djava.library.path="$APPDIR:$APPDIR/lib" -cp "$APPDIR/lib/IRemoconOverNAT_Home.jar:$APPDIR/lib/core.jar:$APPDIR/lib/jogl-all.jar:$APPDIR/lib/gluegen-rt.jar:$APPDIR/lib/jogl-all-natives-linux-amd64.jar:$APPDIR/lib/gluegen-rt-natives-linux-amd64.jar:$APPDIR/lib/mqtt.jar:$APPDIR/lib/org.eclipse.paho.client.mqttv3-1.0.1.jar" IRemoconOverNAT_Home "$@"
